# Generated by Django 4.2.7 on 2023-11-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0002_client_product_delete_cotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='client_email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='name',
            new_name='client_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='client_phone',
        ),
        migrations.CreateModel(
            name='Cotization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotization_created_at', models.DateTimeField(auto_now_add=True)),
                ('cotization_modified_at', models.DateTimeField(auto_now=True)),
                ('cotization_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotizacion.client')),
                ('cotization_products', models.ManyToManyField(to='cotizacion.product')),
            ],
        ),
    ]
