# Generated by Django 4.2.7 on 2023-11-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0003_rename_email_client_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_created_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
