# Generated by Django 4.2.7 on 2023-11-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0004_remove_client_client_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_created_by',
        ),
    ]
